
# Q Creator project include file

#-------------------------------------------------
#
# QtCreator project include file
#
#-------------------------------------------------

#OPTIONPARSER_BASE must be specified by parent calling
# .pro file for this to work properly. The default value
# is :
#OPTIONPARSER_BASE = submodule/optionparser

INCLUDEPATH += $$OPTIONPARSER_BASE/src

HEADERS += $$OPTIONPARSER_BASE/src

